---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.3
branches:
  only:
    - master

before_install:
  - gem install bundler -v 2.0.1

install:
  - bundle install

script:
  - bundle exec rspec
